apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-sample
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '{page-latest-supported-hazelcast}-slim'
  advancedNetwork:
    wan:
    - name: istanbul
      port: 5710
      serviceType: LoadBalancer
